---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-db
  labels:
    app: user-db
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: user-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: user-db
    spec:
      containers:
      - name: user-db
        image: docker.io/library/postgres:16.2
        imagePullPolicy: IfNotPresent
        ports:
        - name: tcp
          containerPort: 5432
        envFrom:
        - configMapRef:
            name: user-db-env
        - secretRef:
            name: user-db-secrets
      terminationGracePeriodSeconds: 180